
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: jdbc:mysql://localhost:3306/movies
    username: root
    password: Bharani170802
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      idle-timeout: 30000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 2000000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: update  # Options: validate, update, create, create-drop
    show-sql: true  # Show SQL queries in the log
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  mail:
    host: smtp.gmail.com
    port: 465
    username: bharanitharan170802@gmail.com
    password: bsooflgcneoxsdgx
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true

logging:
  level:
    org:
      springframework:
        security=DEBUG:

project:
  poster: poster/
base:
  url: "http://localhost:8080"
